name: "Github Tag"
description: "Publish to npm"
author: "Michael Mannseicher"
inputs:
  create_tag:
    description: "Generate an tag"
    required: false
    default: "false"
  project_build_dir:
    description: "The project build directory."
    required: false
    default: "dist"
  auth_token:
    description: "An auth token of your npm account."
    required: true
  install_build_packages:
    description: "Install build packages."
    required: false
    default: "false"
  registry:
    description: "npm registry."
    required: false
    default: "https://registry.npmjs.org/"
outputs:
  published:
    description: "Published new version"
  currentVersion:
    description: "current repository version"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "git-merge"
  color: "purple"
